apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-bddk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-bddk
    app.kubernetes.io/part-of: test-app-twwl
  name: devfile-sample-python-basic-bddk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-bddk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-bddk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-dhdi-tenant/test-app-twwl/devfile-sample-python-basic-bddk@sha256:cc789616177a186aab2e05c0817b8258d159b2011896c268c1965fd035cac14c
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
