apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-bddk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-dhdi-tenant/test-app-twwl/devfile-sample-python-basic-bddk@sha256:cc789616177a186aab2e05c0817b8258d159b2011896c268c1965fd035cac14c
        name: my-python
        resources: {}
status: {}
